version: '3'


services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    container_name: backend-node
    ports:
      - ${PORT}:${PORT}
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: ${PORT}
